### ISSUE TITLE
Bug when ingress definition doesn't contain rules

### ISSUE THREAD

**Issue by jess-sol** [sharifelgamal/minikube-ingress-dns#1]
Currently running into an issue when no rules are defined in an ingress ([just a default backend](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend)).

Example ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: test
      port:
        name: http
```

I believe defaulting to zero [here](https://github.com/sharifelgamal/minikube-ingress-dns/blob/e1273fcd39fa5e08c999b2167091dd780daeab1c/app/dns-server/nodejs/src/index.js#L36) would fix it
